makefile update: working version to include files src/jl2
git-svn-id: https://svn.mcs.anl.gov/repos/NEKCEM/trunk@428 df63514b-fc50-0410-8a93-94e60f5a2dad

diff --git a/bin/arch-settings/linux-pgi-mpi b/bin/arch-settings/linux-pgi-mpi
--- a/bin/arch-settings/linux-pgi-mpi
+++ b/bin/arch-settings/linux-pgi-mpi
@@ -1,14 +1,14 @@
-if ! mpif77 -V 2>&1 | grep -i Portland > /dev/null; then
-  echo "*** error: this arch script is meant to work with the pgi compiler"
-  echo "*** put the following in your $HOME/.soft to use it:"
-  cat <<EOF
-@all-mpich_gm-pgi
-@default
-+pgi
-EOF
-  echo "*** note: order matters. run resoft to enable your settings."
-  exit 1
-fi
+#if ! mpif77 -V 2>&1 | grep -i Portland > /dev/null; then
+#  echo "*** error: this arch script is meant to work with the pgi compiler"
+#  echo "*** put the following in your $HOME/.soft to use it:"
+#  cat <<EOF
+#@all-mpich_gm-pgi
+#@default
+#+pgi
+#EOF
+#  echo "*** note: order matters. run resoft to enable your settings."
+#  exit 1
+#fi
   
 export COMM_BACKEND=comm_mpi
 export IO_BACKEND=vtkbin
